### ISSUE TITLE
Cannot remove services from AS 1001 (and many others)

### ISSUE THREAD

**Issue by mkowalski** [netsec-ethz/scionlab#216]
When trying to remove an arbitrary service from AS 1001, e.g. the last instance of the border router, the following stack trace appears

```
Internal Server Error: /admin/scionlab/as/1/change/
Traceback (most recent call last):
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/core/handlers/exception.py", line 34, in inner
    response = get_response(request)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/core/handlers/base.py", line 115, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/core/handlers/base.py", line 113, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/usr/lib64/python3.7/contextlib.py", line 74, in inner
    return func(*args, **kwds)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 606, in wrapper
    return self.admin_site.admin_view(view)(*args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/views/decorators/cache.py", line 44, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/sites.py", line 223, in inner
    return view(request, *args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1637, in change_view
    return self.changeform_view(request, object_id, form_url, extra_context)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/utils/decorators.py", line 45, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/utils/decorators.py", line 142, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1522, in changeform_view
    return self._changeform_view(request, object_id, form_url, extra_context)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1563, in _changeform_view
    change_message = self.construct_change_message(request, form, formsets, add)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/options.py", line 1050, in construct_change_message
    return construct_change_message(form, formsets, add)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/contrib/admin/utils.py", line 520, in construct_change_message
    'object': str(deleted_object),
  File "/home/kmateusz/git/github.com/scionlab/scionlab/models/core.py", line 1130, in __str__
    return "br-%s-%i" % (self.AS.isd_as_path_str(), self._br_idx())
  File "/home/kmateusz/git/github.com/scionlab/scionlab/models/core.py", line 1134, in _br_idx
    return self.AS.border_routers.filter(pk__lt=self.pk).count() + 1
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/query.py", line 892, in filter
    return self._filter_or_exclude(False, *args, **kwargs)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/query.py", line 910, in _filter_or_exclude
    clone.query.add_q(Q(*args, **kwargs))
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/sql/query.py", line 1290, in add_q
    clause, _ = self._add_q(q_object, self.used_aliases)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/sql/query.py", line 1318, in _add_q
    split_subq=split_subq, simple_col=simple_col,
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/sql/query.py", line 1251, in build_filter
    condition = self.build_lookup(lookups, col, value)
  File "/home/kmateusz/git/github.com/scionlab/venv/lib64/python3.7/site-packages/django/db/models/sql/query.py", line 1121, in build_lookup
    raise ValueError("Cannot use None as a query value")
ValueError: Cannot use None as a query value
```

**Comment by mkowalski** [comment]
My very first suspicion is the following -- error occurs when deleting a border router in a AS which at the moment of the request has existing border router(s) without attached interface(s). Not 100% sure though.

**Comment by mkowalski** [comment]
Apparently it's not true -- AS 1108 has all the border routers used and it's not possible to remove a bwtester from there.
